### ISSUE TITLE
Alt+S repeatedly doesn't cycle between two most recent tabs

### ISSUE THREAD

**Issue by borekb** [harshayburadkar/clut-chrome-extension#3] opened 2016-09-24 12:44 UTC
If I press Alt+S repeatedly (pres Alt+S, release both keys, press Alt+S again, etc.), it should cycle between the two most recent tabs. However, sometimes, it jumps to some other tab, no sure why. Feels like a bug.

**Comment by harshayburadkar** [comment] 2016-09-24 13:21
That is one of the implementation detail issue mainly due to a restriction in the APIs. It is talked about in the FAQ of the extension page. In short as a extension developer Chrome only tells us if Alt and the other key got pressed, but it does not individually tell if only alt or only the other key is pressed. So we do rely on timers and count delay in between the Alt + <other key>, quick switch has lower timer value whereas normal switch has longer. So until the timer is going on even if you release both keys, the extension will behave as if the alt key is still held. If you try your case with higher delays in between your key presses you will get the behavior you want. But of course I would use quick switch key myself if that is the use case you are looking for since it allows for much faster switches due to its lower timer value. 

The problem is that your use case is that of a quick switch but you are using the normal switch key. Go to your extension keyboard shortcut settings, find out the quick switch key and use that instead, you will get better results. I think it defaults to Alt + W.

**Comment by borekb** [comment] 2016-09-24 13:28
Ah ok, I've read the description but couldn't quite understand what the difference is, except Alt+W only cycling between the two most recent tabs and Alt+S doing all the tabs. This technical description you just provided explains it much better, thank you.

Is there a Chromium / Chrome issue about the key press events?

**Comment by borekb** [comment] 2016-09-24 19:54
What's the longer timer limit, by the way? Feels quite long (about 1 second?).

**Comment by harshayburadkar** [comment] 2016-09-27 13:38
There isn't a issue its the way they allowed extension developers to use it. My guess is that they limited the way you can read key presses. They wanted it to allow for keyboard shortcuts but make it difficult for someone to make a key logger out of it, hence reading w or any other letter individually isn't possible using the commands api. Hope that explains it. You can look up for 'commands' inside the manifest.json.
By using other ways(inserting script inside each web page) might slow down usage of websites, hence stayed away from it.

For the other question:
The code does not limit quick switch (default: Alt+w) to 2 tabs, it just uses a smaller timer setting. I myself use Alt+w when I am frequently using 3 tabs, sometimes 4. 
Press Alt+w quickly twice and see what window shows up. It should be the tab previously to previously visited one. 
Timer value is 1500ms for Alt+S.

**Comment by borekb** [comment] 2016-09-27 14:43
So what does the timer really mean? Does it start when I press `Alt`? What happens when the timer reaches 1500ms? I'm asking because sometimes, pressing Alt+S seems to behave weirdly and I'd like to understand why.

**Comment by borekb** [comment] 2016-09-27 14:43
BTW your explanations are much appreciated, @harshayburadkar.

**Comment by harshayburadkar** [comment] 2020-02-16 12:43
I got busy and had lost track of this issue. Closing since it is several years old now. Please reopen if you still want to know more. @borekb

**Closed as completed by harshayburadkar** 2020-02-16 12:43 UTC
